project:
  type: website

website:
  title: "Extreme Weather Events in the States"
  navbar:
    left:
      - href: home.qmd
        text: Home
      - about.qmd
      - href: data.qmd
        text: Data Analyisis
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



