---
title: "Extreme Weather Events in the States"
author: "Serzh"
format: html
editor: visual
execute: 
  echo: false
---

# Introduction to Our Project

Welcome to our comprehensive guide on Extreme Weather Events in the States! With the increasing frequency and intensity of weather phenomena such as hurricanes, wildfires, floods, and tornadoes, it's crucial to understand their impact and how they vary across different regions. Our project aims to provide a detailed analysis of these events, offering insights into patterns, trends, and their implications on communities and the environment.

```{r}
#| message: false

library(dplyr)
library(ggplot2)


file_path <- "/Users/user/Desktop/Final-Project/StormEvents_details-ftp_v1.0_d2022_c20240716.csv"


storm_data <- read.csv(file_path)


filtered_data <- storm_data %>%
  group_by(STATE) %>%
  filter(n() > 2000) %>%
  ungroup()

ggplot(filtered_data, aes(x = STATE,fill = STATE)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle=65, vjust=0.6)) + 
  labs(title = "The States Where Extreme Weather Events Happen the Most (2022)", x = "States", y = "Count of Extreme Weather Events") 




```

# Why Our Project is Important

Understanding extreme weather events is more important than ever. Climate change has led to an increase in the severity and frequency of these events, affecting millions of lives and causing billions in damage. By analyzing and visualizing data on extreme weather, we aim to:

Raise awareness about the growing threat of extreme weather events. Provide valuable information for policymakers and planners to develop better mitigation and adaptation strategies. Help communities prepare for and respond to these events more effectively. Highlight the need for urgent action to combat climate change and protect vulnerable populations. Join us on this journey to uncover the critical insights about extreme weather events and their impact on our world. Together, we can make a difference!

# Inviting and Exciting Design

Our website is designed to be visually appealing and user-friendly, ensuring an engaging experience for all visitors. From vibrant colors that reflect the intensity of extreme weather to interactive elements that allow you to explore data in depth, we've crafted a site that is both informative and captivating.
